"""Initial migration.

Revision ID: 77a0f741ce64
Revises: 
Create Date: 2024-08-24 13:30:14.362520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a0f741ce64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=50), nullable=False, server_default='Unknown'))
        batch_op.drop_column('date')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=50), nullable=False, server_default='Unknown'))
        batch_op.drop_column('year')

    # ### end Alembic commands ###
